### ISSUE TITLE
Use JSON_MultipleHeaders=OFF for nlohmann/json

### ISSUE THREAD

**Issue by hillmich** [cda-tum/qfr#124]
A [recent commit](https://github.com/nlohmann/json/commit/e80945da2cecab8ed1b6a35c4784614801222d58#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a) changed the default behaviour of nlohmann/json to use `JSON_MultipleHeaders=ON` instead of `OFF`.

This breaks at least the build from sdist for DDSIM (which prunes the multiple header folder). This is locally fixable by setting the option accordingly (or use the multiple headers). 

Question: Should we set `JSON_MultipleHeaders=OFF` in the qfr via `set(JSON_MultipleHeaders OFF CACHE INTERNAL "")` at the appropriate location?

**Comment by burgholzer** [comment]
From my point of view, we could also opt into using the multiple header format. I guess the benefit would be slightly faster compile times.
Any disadvantage? Other than having to adapt our high-level projects.

**Comment by hillmich** [comment]
I don't see how the multiple header version leads to faster compile times, since it provides the same header-only functionality but requires opening and reading multiple files (at most the multiple header version might be milliseconds slower).

So far we implicitly used the single header version and the question is only whether we should switch or make this decision explicit. I'm in favor of the single header version.

**Comment by burgholzer** [comment]
Fine with me. Feel free to go ahead and open a PR for that 👍🏼
